language: elixir

elixir: "1.8"

env:
  - MIX_ENV=test

services:
  - docker

before_install:
  - docker pull floatingghost/misp-testable:v2.4.102
  - docker run -d -p 80:80 floatingghost/misp-testable:v2.4.102

install:
  - cp config/travis.exs config/test.exs
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get 

script:
  - mix test
